import { Response, NextFunction } from 'express';
import { AuthRequest } from '../../middlewares/requireAuth';
import { NotificationService } from './notification.service';

export const getNotifications = async (req: AuthRequest, res: Response, next: NextFunction) => {
  try {
    const userId = req.user!.userId;
    const notifications = await NotificationService.getNotifications(userId);
    res.status(200).json({ success: true, data: notifications });
  } catch (error) {
    next(error);
  }
};

export const markAsRead = async (req: AuthRequest, res: Response, next: NextFunction) => {
  try {
    const userId = req.user!.userId;
    const { id } = req.params;
    await NotificationService.markAsRead(id, userId);
    res.status(200).json({ success: true, message: 'Notification marked as read' });
  } catch (error) {
    next(error);
  }
};

export const markAllAsRead = async (req: AuthRequest, res: Response, next: NextFunction) => {
  try {
    const userId = req.user!.userId;
    await NotificationService.markAllAsRead(userId);
    res.status(200).json({ success: true, message: 'All notifications marked as read' });
  } catch (error) {
    next(error);
  }
};

// This is a test endpoint to manually trigger a notification for debugging
export const createTestNotification = async (req: AuthRequest, res: Response, next: NextFunction) => {
  try {
    const userId = req.user!.userId;
    const notification = await NotificationService.createNotification(
      userId,
      'SYSTEM_ALERT',
      'Test Notification',
      'This is a test notification generated by the user',
      { isTest: true }
    );
    res.status(201).json({ success: true, data: notification });
  } catch (error) {
    next(error);
  }
};
